"""initial

Revision ID: 83b36fedbc31
Revises: 
Create Date: 2022-09-16 13:15:49.237248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b36fedbc31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('parent_id', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=36), nullable=False),
    sa.Column('email', sa.VARCHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('orders',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('user_id', sa.SmallInteger(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('data_create', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('article', sa.CHAR(length=6), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('date_create', sa.TIMESTAMP(), nullable=True),
    sa.Column('descr', sa.VARCHAR(length=140), nullable=True),
    sa.Column('category_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article')
    )
    op.create_table('orders_items',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('product_article', sa.CHAR(length=6), nullable=False),
    sa.Column('order_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_article'], ['products.article'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_items')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
